import { clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs) {
  return twMerge(clsx(inputs))
}

export const banks = [
  { id: 1, name: 'AB Bank PLC' },
  { id: 2, name: 'Agrani Bank PLC' },
  { id: 3, name: 'Al-Arafah Islami Bank PLC' },
  { id: 4, name: 'Bangladesh Commerce Bank Limited' },
  { id: 5, name: 'Bangladesh Development Bank PLC' },
  { id: 6, name: 'Bangladesh Krishi Bank' },
  { id: 7, name: 'Bank Al-Falah Limited' },
  { id: 8, name: 'Bank Asia PLC.' },
  { id: 9, name: 'BASIC Bank Limited' },
  { id: 10, name: 'Bengal Commercial Bank PLC.' },
  { id: 11, name: 'BRAC Bank PLC' },
  { id: 12, name: 'Citibank N.A' },
  { id: 13, name: 'Citizens Bank PLC' },
  { id: 14, name: 'City Bank PLC' },
  { id: 15, name: 'Commercial Bank of Ceylon Limited' },
  { id: 16, name: 'Community Bank Bangladesh PLC.' },
  { id: 17, name: 'Dhaka Bank PLC' },
  { id: 18, name: 'Dutch-Bangla Bank PLC' },
  { id: 19, name: 'Eastern Bank PLC' },
  { id: 20, name: 'EXIM Bank PLC' },
  { id: 21, name: 'First Security Islami Bank PLC' },
  { id: 22, name: 'Global Islami Bank PLC' },
  { id: 23, name: 'Habib Bank Ltd.' },
  { id: 24, name: 'ICB Islamic Bank Ltd.' },
  { id: 25, name: 'IFIC Bank PLC' },
  { id: 26, name: 'Islami Bank Bangladesh PLC' },
  { id: 27, name: 'Jamuna Bank PLC' },
  { id: 28, name: 'Janata Bank PLC' },
  { id: 29, name: 'Meghna Bank PLC' },
  { id: 30, name: 'Mercantile Bank PLC' },
  { id: 31, name: 'Midland Bank Limited' },
  { id: 32, name: 'Modhumoti Bank PLC' },
  { id: 33, name: 'Mutual Trust Bank PLC' },
  { id: 34, name: 'Nagad Digital Bank PLC.' },
  { id: 35, name: 'National Bank Limited' },
  { id: 36, name: 'National Bank of Pakistan' },
  { id: 37, name: 'National Credit & Commerce Bank PLC' },
  { id: 38, name: 'NRB Bank Limited' },
  { id: 39, name: 'NRBC Bank PLC' },
  { id: 40, name: 'One Bank PLC' },
  { id: 41, name: 'Padma Bank PLC' },
  { id: 42, name: 'Prime Bank PLC' },
  { id: 43, name: 'Probashi Kollyan Bank' },
  { id: 44, name: 'Pubali Bank PLC' },
  { id: 45, name: 'Rajshahi Krishi Unnayan Bank' },
  { id: 46, name: 'Rupali Bank PLC' },
  { id: 47, name: 'SBAC Bank PLC' },
  { id: 48, name: 'Shahjalal Islami Bank PLC' },
  { id: 49, name: 'Shimanto Bank PLC' },
  { id: 50, name: 'Social Islami Bank PLC' },
  { id: 51, name: 'Sonali Bank PLC' },
  { id: 52, name: 'Southeast Bank PLC' },
  { id: 53, name: 'Standard Bank PLC' },
  { id: 54, name: 'Standard Chartered Bank' },
  { id: 55, name: 'State Bank of India' },
  { id: 56, name: 'The Hong Kong and Shanghai Banking Corporation. Ltd.' },
  { id: 57, name: 'The Premier Bank PLC' },
  { id: 58, name: 'Trust Bank Limited' },
  { id: 59, name: 'Union Bank PLC' },
  { id: 60, name: 'United Commercial Bank PLC' },
  { id: 61, name: 'Uttara Bank PLC' },
  { id: 62, name: 'Woori Bank' },
];

export const mfsList = [
    { id: 1, name: 'bKash' },
    { id: 2, name: 'Nagad' },
    { id: 3, name: 'ROCKET' },
    { id: 4, name: 'উপায় (Upay' },
    { id: 5, name: 'MYCash' },
    { id: 6, name: 'Trust Axiata pay: tap' },
    { id: 7, name: 'Islami Bank mCash' },
    { id: 8, name: 'OK Wallet' },
    { id: 9, name: 'Rupali Bank' },
    { id: 10, name: 'TeleCash' },
    { id: 11, name: 'Islamic Wallet' },
    { id: 12, name: 'Meghna Pay' },
    { id: 13, name: 'FirstCash' },
    ];